// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimeEntrySystem.API.Data;

namespace TimeEntrySystem.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190216213309_EmployeeCreated")]
    partial class EmployeeCreated
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ChangeDetector.SkipDetectChanges", "true")
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034");
#pragma warning restore 612, 618
        }
    }
}
